mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.post_list, name='post list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_details,
         name='post_details'),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('production/', views.production_view, name='production'),
    path('exchange/', views.exchange_view, name='exchange'),
]

mysite/mysite/urls.py
from django.urls import include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.contrib import admin
from django.urls import path


"""
URL configuration for mysite project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Summary(models.Model):
    timestamp = models.CharField(unique=True, max_length=255, null=False)
    czas = models.DateTimeField(default=timezone.now(), null=False)
    status = models.IntegerField(null=False)
    wodne = models.IntegerField(null=False)
    wiatrowe = models.IntegerField(null=False)
    PV = models.IntegerField(null=False)
    generacja = models.IntegerField(null=False)
    zapotrzebowanie = models.IntegerField(null=False)
    czestotliwosc = models.FloatField(null=False)
    inne = models.IntegerField(null=False)
    cieplne = models.IntegerField(null=False)

    def __str__(self):
        return self.timestamp


class Connections(models.Model):
    timestamp_id = models.CharField(unique=True, max_length=255, null=False)
    timestamp = models.CharField(max_length=255, null=False)
    czas = models.DateTimeField(default=timezone.now(), null=False)
    status = models.IntegerField(null=False)
    ID = models.CharField(max_length=5, null=False)
    wartosc = models.IntegerField(null=False)
    rownolegly = models.IntegerField(null=False)
    wartosc_plan = models.IntegerField(null=False)

    def __str__(self):
        return self.timestamp

    def __repr__(self):
        return self.ID


class Exchanges(models.Model):
    timestamp = models.CharField(unique=True, max_length=255, null=False)
    status = models.IntegerField(null=False)
    czas = models.DateTimeField(default=timezone.now(), null=False)
    eksport = models.IntegerField(null=False)
    importt = models.IntegerField(null=False)
    saldo = models.IntegerField(null=False)

    def __str__(self):
        return self.timestamp


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    object = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_details',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Komentarz dodany przez {} dla posta {}'.format(self.name, self.post)

mysite/blog/forms.py
from django import forms
from .models import Comment, Summary


class SearchForm(forms.Form):
     query = forms.CharField()


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Summary, Connections, Exchanges
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
import requests
import json


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + \
                            SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.object.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.2).order_by('-rank')
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})


def post_share(request, post_id):
    # Pobranie posta na podstawie jego identyfikatora
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Formularz zostal wyslany
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Weryfikacja pól formularza zakończyła siępowodzeniem...
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = '{} ({}) zachęca do przeczytania "{}"', format(cd['name'],
                                                                     cd['email'], post.title)
            message = 'Przeczytaj post "{}" na stronie {}\n\n Komentarz dodany przez: {}: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
            # Więc można wysłać maila
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # trzy posty na kazdej stronie
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # jezeli zmienna page nie jest liczba calkowita
        # wowczas pobierana jest pierwsza strona wynikow
        posts = paginator.page(1)
    except EmptyPage:
        # jezeli zmienna page ma wartosc wieksza niz numer ostatniej strony
        # wynikow wtedy pobierana jest ostatnia strona wynikow.
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_details(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Lista aktywnych komentarzy dla danego posta
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # Komentarz opublikowany
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Utworzenie obiektu comment: jeszcze jednak nie zapisujemy go w bazie danych
            new_comment = comment_form.save(commit=False)
            # Przypisanie komentarza do bieżącego posta
            new_comment.post = post
            # Zapisanie komentarza wbazie danych
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
        .order_by('-same_tags', '-publish')[:4]
    return render(request,
                  'blog/post/details.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def production_view(request):
    URL = "https://www.pse.pl/transmissionMapService"
    page = requests.get(URL)

    datas = json.loads(page.text)

    current_data = Summary()
    try:
        if request.method == "GET" or request.method == "POST":
            current_data.status = datas['status']
            current_data.czas = datetime.datetime.now()
            current_data.timestamp = datas['timestamp']
            current_data.PV = datas['data']['podsumowanie']['PV']
            current_data.cieplne = datas['data']['podsumowanie']['cieplne']
            current_data.czestotliwosc = datas['data']['podsumowanie']['czestotliwosc']
            current_data.generacja = datas['data']['podsumowanie']['generacja']
            current_data.inne = datas['data']['podsumowanie']['inne']
            current_data.wiatrowe = datas['data']['podsumowanie']['wiatrowe']
            current_data.wodne = datas['data']['podsumowanie']['wodne']
            current_data.zapotrzebowanie = datas['data']['podsumowanie']['zapotrzebowanie']
    except:
        pass


    return render(request,
                  'blog/production.html',
                  {'current_data': current_data,
                   }
                  )

def exchange_view(request):
    URL = "https://www.pse.pl/transmissionMapService"
    page = requests.get(URL)
    datas = json.loads(page.text)
    connections_data_se = Connections()
    connections_data_cz = Connections()
    connections_data_de = Connections()
    connections_data_sk = Connections()
    connections_data_ua = Connections()
    connections_data_lt = Connections()
    exchanges_data = Exchanges()
    eksport, importt = exchanges_calculation(datas)
    saldo = eksport + importt

    try:
        if request.method == "GET" or request.method == "POST":
            exchanges_data.timestamp = datas['timestamp']
            exchanges_data.czas = datetime.datetime.now()
            exchanges_data.eksport = abs(eksport)
            exchanges_data.importt = importt
            exchanges_data.saldo = saldo

            connections_data_se.wartosc = datas['data']['przesyly'][0]['wartosc']
            connections_data_se.wartosc_plan = datas['data']['przesyly'][0]['wartosc_plan']
            connections_data_cz.wartosc = datas['data']['przesyly'][2]['wartosc']
            connections_data_cz.wartosc_plan = datas['data']['przesyly'][2]['wartosc_plan']
            connections_data_de.wartosc = datas['data']['przesyly'][1]['wartosc']
            connections_data_de.wartosc_plan = datas['data']['przesyly'][1]['wartosc_plan']
            connections_data_sk.wartosc = datas['data']['przesyly'][3]['wartosc']
            connections_data_sk.wartosc_plan = datas['data']['przesyly'][3]['wartosc_plan']
            connections_data_ua.wartosc = datas['data']['przesyly'][4]['wartosc']
            connections_data_ua.wartosc_plan = datas['data']['przesyly'][4]['wartosc_plan']
            connections_data_lt.wartosc = datas['data']['przesyly'][5]['wartosc']
            connections_data_lt.wartosc_plan = datas['data']['przesyly'][5]['wartosc_plan']
    except:
        pass


    return render(request,
                  'blog/exchange.html',
                  {'connections_data_se': connections_data_se,
                   'connections_data_cz': connections_data_cz,
                   'connections_data_de': connections_data_de,
                   'connections_data_sk': connections_data_sk,
                   'connections_data_ua': connections_data_ua,
                   'connections_data_lt': connections_data_lt,
                   'exchanges_data': exchanges_data,
                   }
                  )


def exchanges_calculation(datas):
    eksport, importt = 0, 0
    for _ in datas['data']['przesyly']:
        if _['wartosc'] > 0:
            importt += _['wartosc']
        elif _['wartosc'] <= 0:
            eksport += _['wartosc']

    return eksport, importt

mysite/blog/templates/blog/post/details.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} {{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{post.body|markdown}}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Udostępnij post
        </a>
    </p>
    <h2>Podobne posty</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Nie ma podobnych postów.
    {% endfor %}
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments}} komentarz{{ total_comments | pluralize:"y" }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Komentarz {{ forloop.counter }} dodany przez {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>Nie ma jeszcze komentarzy.</p>
  {% endfor %}
  {% if new_comment %}
    <h2>Twój komentarz został dodany.</h2>
  {% else %}
    <h2>Dodaj nowy komentarz.</h2>
    <form method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Dodaj komentarz"></p>
    </form>
  {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Mój blog{% endblock %}

{% block content %}
  <h1>Mój blog</h1>
  {% if tag %}
    <h2>Posty oznaczone tagiem "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
        {{ post.body|markdown|truncatewords_html:30 }}
        <p class="tags">
          Tagi:
          {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
              {{ tag.name }}
            </a>
              {% if not forloop.last %}, {% endif %}
          {% endfor %}
      </p>
    </h2>
    <p class="date">
      Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Szukaj{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posty zawierające "{{ query }}"</h1>
        <h3>Znaleziono {{ total_results }} wynik{{ total_results|pluralize:"i" }}</h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p>Brak wyników zapytania</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Szukaj ponownie</a></p>
    {% else %}
        <h1>Szukaj postów</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value ="Szukaj">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>Wiadomość e-mail zostałą wysłąna</h1>
    <p>
      Wysłanie posta "{{ post.title }}" do {{ form.cleaned_data.to }} zakończyło się sukcesem.
    </p>
  {% else %}
    <h1>Udostępnij "{{ post.title }}" przez e-mail </h1>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Wyślij wiadomość e-mail">
    </form>
  {% endif %}
{% endblock %}